version: "{build}"
platform: x64
clone_folder: c:\gopath\src\github.com\borg323\lczero-client

environment:
  GOPATH: c:\gopath;c:\gopath\src\github.com\borg323\lczero-client\
  matrix:
  - NAME: .exe
    GOOS: windows
  - NAME: _linux
    GOOS: linux
  - NAME: mac
    GOOS: darwin
install:
  - go get -u github.com/Tilps/chess
build_script:
  - go build -o client%NAME% lc0_main.go
artifacts:
  - path: client$(NAME)
    name: client
deploy:
  - provider: GitHub
    artifact: client%NAME%
    auth_token:
    secure: ILgB4aHwek0Pb2YWho/FKzkUy3rAPL0bIV+F+g385mMxa6zDXV1YdjJ6NgHC70lU
    on:
      appveyor_repo_tag: true

